# Site settings
title: rust-wiiu
description: Rust on the Nintendo Wii U
url: "https://rust-wiiu.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["README.md"]

# Theme settings (using minimal Jekyll setup)
sass:
  sass_dir: assets/css
  style: compressed