name: Sitemap Generator

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v5
      - name: Generate Sitemap
        run: |
          npx sitemap-generator-cli https://rust-wiiu.github.io/ -l -p "1.0,0.8,0.6,0.4" -g "monthly"
          if [ ! -s sitemap.xml ]; then
            echo "Error: sitemap.xml was not generated or is empty."
            exit 1
          fi
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update sitemap.xml
          file_pattern: sitemap.xml