name: Sitemap Generator

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://rust-wiiu.github.io/
          sitemap-format: xml
          output-path: sitemap.xml
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update sitemap.xml
          file_pattern: sitemap.xml